<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Rahee-Khan" failures="1" tests="2" name="Test_E2E_03_iOS" time="277.163" errors="0" timestamp="2023-11-16T18:07:21 EST">
  <testcase classname="web_tests.MainPageTests" name="validate_title_test" time="7.428"/>
  <testcase classname="mobile_tests.PaymentTests" name="verify_user_making_payment" time="24.738">
    <failure type="java.lang.AssertionError" message="Amount has not been deducted. did not expect [35000] but found [35000]">
      <![CDATA[java.lang.AssertionError: Amount has not been deducted. did not expect [35000] but found [35000]
at mobile_tests.PaymentTests.verify_user_making_payment(PaymentTests.java:86)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- verify_user_making_payment -->
</testsuite> <!-- Test_E2E_03_iOS -->
